GRANT CONNECT ON DATABASE app_administration TO uah;
GRANT USAGE ON SCHEMA public TO uah;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO uah;
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA public TO uah;